#!/bin/sh
PREREQ="cloud-initramfs-dyn-netconf"
prereqs()
{
  echo "$PREREQ"
}

case $1 in
prereqs)
  prereqs
  exit 0
  ;;
esac

# shellcheck disable=SC1091
. /usr/share/initramfs-tools/hook-functions

copy_file regular /etc/public.pem /etc/
copy_file regular /etc/private.pem /etc/
copy_file regular /etc/config.json /etc/
copy_file regular /etc/ssl/certs/GlobalSign_Root_R46.pem  /etc/ssl/
copy_file regular /etc/ssl/certs/BJCA_Global_Root_CA1.pem /etc/ssl/
copy_file regular /etc/ssl/certs/Entrust_Root_Certification_Authority_-_G2.pem /etc/ssl/
copy_file regular /etc/ssl/certs/GlobalSign_Root_CA_-_R3.pem /etc/ssl/
copy_file regular /etc/ssl/certs/QuoVadis_Root_CA_2_G3.pem /etc/ssl/
copy_file regular /etc/ssl/certs/SSL.com_EV_Root_Certification_Authority_RSA_R2.pem /etc/ssl/
copy_file regular /etc/ssl/certs/Security_Communication_RootCA3.pem /etc/ssl/
copy_file regular /etc/ssl/certs/Starfield_Services_Root_Certificate_Authority_-_G2.pem /etc/ssl/
copy_file regular /etc/ssl/certs/GTS_Root_R3.pem /etc/ssl/
copy_file regular /etc/ssl/certs/CFCA_EV_ROOT.pem /etc/ssl/
copy_file regular /etc/ssl/certs/ISRG_Root_X2.pem /etc/ssl/
copy_file regular /etc/ssl/certs/SSL.com_Root_Certification_Authority_ECC.pem /etc/ssl/
copy_file regular /etc/ssl/certs/UCA_Extended_Validation_Root.pem /etc/ssl/
copy_file regular /etc/ssl/certs/GDCA_TrustAUTH_R5_ROOT.pem /etc/ssl/
copy_file regular /etc/ssl/certs/GTS_Root_R1.pem /etc/ssl/
copy_file regular /etc/ssl/certs/Entrust_Root_Certification_Authority_-_EC1.pem /etc/ssl/
copy_file regular /etc/ssl/certs/emSign_ECC_Root_CA_-_G3.pem /etc/ssl/
copy_file regular /etc/ssl/certs/SecureSign_RootCA11.pem /etc/ssl/
copy_file regular /etc/ssl/certs/TrustAsia_Global_Root_CA_G4.pem /etc/ssl/
copy_file regular /etc/ssl/certs/GlobalSign_ECC_Root_CA_-_R5.pem /etc/ssl/
copy_file regular /etc/ssl/certs/IdenTrust_Public_Sector_Root_CA_1.pem /etc/ssl/
copy_file regular /etc/ssl/certs/T-TeleSec_GlobalRoot_Class_2.pem /etc/ssl/
copy_file regular /etc/ssl/certs/CommScope_Public_Trust_ECC_Root-01.pem /etc/ssl/
copy_file regular /etc/ssl/certs/DigiCert_High_Assurance_EV_Root_CA.pem /etc/ssl/
copy_file regular /etc/ssl/certs/emSign_Root_CA_-_G1.pem /etc/ssl/
copy_file regular /etc/ssl/certs/CA_Disig_Root_R2.pem /etc/ssl/
copy_file regular /etc/ssl/certs/AffirmTrust_Commercial.pem /etc/ssl/
copy_file regular /etc/ssl/certs/Hellenic_Academic_and_Research_Institutions_RootCA_201 /etc/ssl/
copy_file regular /etc/ssl/certs/DigiCert_Global_Root_CA.pem /etc/ssl/
copy_file regular /etc/ssl/certs/Autoridad_de_Certificacion_Firmaprofesional_CIF_A62634 /etc/ssl/
copy_file regular /etc/ssl/certs/BJCA_Global_Root_CA2.pem /etc/ssl/
copy_file regular /etc/ssl/certs/NAVER_Global_Root_Certification_Authority.pem /etc/ssl/
copy_file regular /etc/ssl/certs/Certum_Trusted_Network_CA_2.pem /etc/ssl/
copy_file regular /etc/ssl/certs/ISRG_Root_X1.pem /etc/ssl/
copy_file regular /etc/ssl/certs/COMODO_Certification_Authority.pem /etc/ssl/
copy_file regular /etc/ssl/certs/emSign_Root_CA_-_C1.pem /etc/ssl/
copy_file regular /etc/ssl/certs/Certum_Trusted_Network_CA.pem /etc/ssl/
copy_file regular /etc/ssl/certs/emSign_ECC_Root_CA_-_C3.pem /etc/ssl/
copy_file regular /etc/ssl/certs/Starfield_Root_Certificate_Authority_-_G2.pem /etc/ssl/
copy_file regular /etc/ssl/certs/SwissSign_Gold_CA_-_G2.pem /etc/ssl/
copy_file regular /etc/ssl/certs/CommScope_Public_Trust_RSA_Root-02.pem /etc/ssl/
copy_file regular /etc/ssl/certs/T-TeleSec_GlobalRoot_Class_3.pem /etc/ssl/
copy_file regular /etc/ssl/certs/Buypass_Class_2_Root_CA.pem /etc/ssl/
copy_file regular /etc/ssl/certs/SwissSign_Silver_CA_-_G2.pem /etc/ssl/
copy_file regular /etc/ssl/certs/Security_Communication_ECC_RootCA1.pem /etc/ssl/
copy_file regular /etc/ssl/certs/D-TRUST_EV_Root_CA_1_2020.pem /etc/ssl/
copy_file regular /etc/ssl/certs/GlobalSign_Root_CA.pem /etc/ssl/
copy_file regular /etc/ssl/certs/TeliaSonera_Root_CA_v1.pem /etc/ssl/
copy_file regular /etc/ssl/certs/Entrust_Root_Certification_Authority_-_G4.pem /etc/ssl/
copy_file regular /etc/ssl/certs/TWCA_Global_Root_CA.pem /etc/ssl/
copy_file regular /etc/ssl/certs/certSIGN_Root_CA_G2.pem /etc/ssl/
copy_file regular /etc/ssl/certs/DigiCert_Global_Root_G2.pem /etc/ssl/
copy_file regular /etc/ssl/certs/GTS_Root_R2.pem /etc/ssl/
copy_file regular /etc/ssl/certs/Baltimore_CyberTrust_Root.pem /etc/ssl/
copy_file regular /etc/ssl/certs/Hongkong_Post_Root_CA_3.pem /etc/ssl/
copy_file regular /etc/ssl/certs/Entrust_Root_Certification_Authority.pem /etc/ssl/
copy_file regular /etc/ssl/certs/Amazon_Root_CA_2.pem /etc/ssl/
copy_file regular /etc/ssl/certs/SSL.com_Root_Certification_Authority_RSA.pem /etc/ssl/
copy_file regular /etc/ssl/certs/XRamp_Global_CA_Root.pem /etc/ssl/
copy_file regular /etc/ssl/certs/QuoVadis_Root_CA_1_G3.pem /etc/ssl/
copy_file regular /etc/ssl/certs/DigiCert_Trusted_Root_G4.pem /etc/ssl/
copy_file regular /etc/ssl/certs/QuoVadis_Root_CA_3.pem /etc/ssl/
copy_file regular /etc/ssl/certs/Hellenic_Academic_and_Research_Institutions_ECC_RootCA /etc/ssl/
copy_file regular /etc/ssl/certs/OISTE_WISeKey_Global_Root_GC_CA.pem /etc/ssl/
copy_file regular /etc/ssl/certs/vTrus_Root_CA.pem /etc/ssl/
copy_file regular /etc/ssl/certs/Certainly_Root_R1.pem /etc/ssl/
copy_file regular /etc/ssl/certs/DigiCert_Assured_ID_Root_G3.pem /etc/ssl/
copy_file regular /etc/ssl/certs/Microsec_e-Szigno_Root_CA_2009.pem /etc/ssl/
copy_file regular /etc/ssl/certs/CommScope_Public_Trust_ECC_Root-02.pem /etc/ssl/
copy_file regular /etc/ssl/certs/CommScope_Public_Trust_RSA_Root-01.pem /etc/ssl/
copy_file regular /etc/ssl/certs/Certainly_Root_E1.pem /etc/ssl/
copy_file regular /etc/ssl/certs/SSL.com_TLS_ECC_Root_CA_2022.pem /etc/ssl/
copy_file regular /etc/ssl/certs/Amazon_Root_CA_3.pem /etc/ssl/
copy_file regular /etc/ssl/certs/certSIGN_ROOT_CA.pem /etc/ssl/
copy_file regular /etc/ssl/certs/Microsoft_ECC_Root_Certificate_Authority_2017.pem /etc/ssl/
copy_file regular /etc/ssl/certs/Telia_Root_CA_v2.pem /etc/ssl/
copy_file regular /etc/ssl/certs/Sectigo_Public_Server_Authentication_Root_R46.pem /etc/ssl/
copy_file regular /etc/ssl/certs/HiPKI_Root_CA_-_G1.pem /etc/ssl/
copy_file regular /etc/ssl/certs/Actalis_Authentication_Root_CA.pem /etc/ssl/
copy_file regular /etc/ssl/certs/AffirmTrust_Networking.pem /etc/ssl/
copy_file regular /etc/ssl/certs/Certum_EC-384_CA.pem /etc/ssl/
copy_file regular /etc/ssl/certs/DigiCert_TLS_ECC_P384_Root_G5.pem /etc/ssl/
copy_file regular /etc/ssl/certs/'NetLock_Arany_=Class_Gold=_Főtanúsítvány.pem' /etc/ssl/
copy_file regular /etc/ssl/certs/Atos_TrustedRoot_Root_CA_RSA_TLS_2021.pem /etc/ssl/
copy_file regular /etc/ssl/certs/Trustwave_Global_ECC_P256_Certification_Authority.pem /etc/ssl/
copy_file regular /etc/ssl/certs/TrustAsia_Global_Root_CA_G3.pem /etc/ssl/
copy_file regular /etc/ssl/certs/AffirmTrust_Premium_ECC.pem /etc/ssl/
copy_file regular /etc/ssl/certs/DigiCert_Assured_ID_Root_G2.pem /etc/ssl/
copy_file regular /etc/ssl/certs/D-TRUST_BR_Root_CA_1_2020.pem /etc/ssl/
copy_file regular /etc/ssl/certs/HARICA_TLS_RSA_Root_CA_2021.pem /etc/ssl/
copy_file regular /etc/ssl/certs/GTS_Root_R4.pem /etc/ssl/
copy_file regular /etc/ssl/certs/SSL.com_TLS_RSA_Root_CA_2022.pem /etc/ssl/
copy_file regular /etc/ssl/certs/ACCVRAIZ1.pem /etc/ssl/
copy_file regular /etc/ssl/certs/GlobalSign_ECC_Root_CA_-_R4.pem /etc/ssl/
copy_file regular /etc/ssl/certs/DigiCert_Assured_ID_Root_CA.pem /etc/ssl/
copy_file regular /etc/ssl/certs/ANF_Secure_Server_Root_CA.pem /etc/ssl/
copy_file regular /etc/ssl/certs/Secure_Global_CA.pem /etc/ssl/
copy_file regular /etc/ssl/certs/AffirmTrust_Premium.pem /etc/ssl/
copy_file regular /etc/ssl/certs/TWCA_Root_Certification_Authority.pem /etc/ssl/
copy_file regular /etc/ssl/certs/AC_RAIZ_FNMT-RCM_SERVIDORES_SEGUROS.pem /etc/ssl/
copy_file regular /etc/ssl/certs/GlobalSign_ECC_Root_CA_-_R4.pem /etc/ssl/
copy_file regular /etc/ssl/certs/DigiCert_Assured_ID_Root_CA.pem /etc/ssl/
copy_file regular /etc/ssl/certs/ANF_Secure_Server_Root_CA.pem /etc/ssl/
copy_file regular /etc/ssl/certs/Secure_Global_CA.pem /etc/ssl/
copy_file regular /etc/ssl/certs/AffirmTrust_Premium.pem /etc/ssl/
copy_file regular /etc/ssl/certs/TWCA_Root_Certification_Authority.pem /etc/ssl/
copy_file regular /etc/ssl/certs/AC_RAIZ_FNMT-RCM_SERVIDORES_SEGUROS.pem /etc/ssl/
copy_file regular /etc/ssl/certs/D-TRUST_Root_Class_3_CA_2_EV_2009.pem /etc/ssl/
copy_file regular /etc/ssl/certs/DigiCert_TLS_RSA4096_Root_G5.pem /etc/ssl/
copy_file regular /etc/ssl/certs/COMODO_RSA_Certification_Authority.pem /etc/ssl/
copy_file regular /etc/ssl/certs/QuoVadis_Root_CA_2.pem /etc/ssl/
copy_file regular /etc/ssl/certs/Trustwave_Global_ECC_P384_Certification_Authority.pem /etc/ssl/
copy_file regular /etc/ssl/certs/Sectigo_Public_Server_Authentication_Root_E46.pem /etc/ssl/
copy_file regular /etc/ssl/certs/GlobalSign_Root_CA_-_R6.pem /etc/ssl/
copy_file regular /etc/ssl/certs/DigiCert_Global_Root_G3.pem /etc/ssl/
copy_file regular /etc/ssl/certs/Amazon_Root_CA_4.pem /etc/ssl/
copy_file regular /etc/ssl/certs/Go_Daddy_Class_2_CA.pem /etc/ssl/
copy_file regular /etc/ssl/certs/SSL.com_EV_Root_Certification_Authority_ECC.pem /etc/ssl/
copy_file regular /etc/ssl/certs/Trustwave_Global_Certification_Authority.pem /etc/ssl/
copy_file regular /etc/ssl/certs/USERTrust_ECC_Certification_Authority.pem /etc/ssl/
copy_file regular /etc/ssl/certs/Security_Communication_Root_CA.pem /etc/ssl/
copy_file regular /etc/ssl/certs/Starfield_Class_2_CA.pem /etc/ssl/
copy_file regular /etc/ssl/certs/SecureTrust_CA.pem /etc/ssl/
copy_file regular /etc/ssl/certs/Certigna_Root_CA.pem /etc/ssl/
copy_file regular /etc/ssl/certs/GLOBALTRUST_2020.pem /etc/ssl/
copy_file regular /etc/ssl/certs/Atos_TrustedRoot_Root_CA_ECC_TLS_2021.pem /etc/ssl/
copy_file regular /etc/ssl/certs/USERTrust_RSA_Certification_Authority.pem /etc/ssl/
copy_file regular /etc/ssl/certs/TunTrust_Root_CA.pem /etc/ssl/
copy_file regular /etc/ssl/certs/SZAFIR_ROOT_CA2.pem /etc/ssl/
copy_file regular /etc/ssl/certs/GlobalSign_Root_E46.pem /etc/ssl/
copy_file regular /etc/ssl/certs/TUBITAK_Kamu_SM_SSL_Kok_Sertifikasi_-_Surum_1.pem /etc/ssl/
copy_file regular /etc/ca-certificates.conf /etc/ca-certificates.conf
