#!/bin/sh
PREREQ="cloud-initramfs-dyn-netconf"
prereqs()
{
  echo "$PREREQ"
}

case $1 in
prereqs)
  prereqs
  exit 0
  ;;
esac

# shellcheck disable=SC1091
. /usr/share/initramfs-tools/hook-functions

copy_file regular /etc/public.pem /etc/
#copy_file regular /etc/private.pem /etc/
